# Generated by Django 3.1.4 on 2021-06-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
